---
platform: linux
image_resource:
  type: docker-image
  source: {repository: quay.io/desource/alpine, tag: build}
  
run:
  path: container/build.sh
    
inputs:
  - name: container

outputs:
  - name: out
